import {
  dockerProjectName,
  labelsForProject,
  projectContainerName,
  projectNetworkName,
} from "./naming";
import { validateProjectPorts } from "./ports";
import type { ProjectId, ProjectPorts } from "./types";
import type { PlannedVolume } from "./volumes";

export interface NamedVolumeMount {
  readonly service: string;
  readonly purpose: PlannedVolume["purpose"];
  readonly target: string;
  readonly readOnly?: boolean;
}

export interface ComposeOverrideOptions {
  readonly projectId: ProjectId;
  readonly release: string;
  readonly ports: ProjectPorts;
  readonly volumes: readonly PlannedVolume[];
  /** Exact official service names and container targets from the selected release adapter. */
  readonly mounts: readonly NamedVolumeMount[];
  readonly services: readonly string[];
  readonly gatewayService: string;
  readonly realtimeService?: string;
  readonly gatewayEntrypoint?: readonly string[];
}

function safeName(value: string, label: string): string {
  if (!/^[a-zA-Z0-9][a-zA-Z0-9_.-]*$/.test(value)) throw new Error(`${label} is not name safe`);
  return value;
}

function yamlScalar(value: string): string {
  return JSON.stringify(value);
}

/**
 * Generates an override only. The pinned upstream Compose file is never edited.
 * !override is supported by Compose v2 and prevents upstream bind mounts from
 * being merged back into the service volume list.
 */
export function generateComposeOverride(options: ComposeOverrideOptions): string {
  const ports = validateProjectPorts(options.ports);
  const volumeByPurpose = new Map(options.volumes.map((volume) => [volume.purpose, volume.name]));
  const mounts = [...options.mounts].sort((a, b) => a.service.localeCompare(b.service) || a.target.localeCompare(b.target));
  for (const mount of mounts) {
    safeName(mount.service, "service");
    if (!mount.target.startsWith("/")) throw new Error("volume target must be absolute");
    if (!volumeByPurpose.has(mount.purpose)) throw new Error(`volume plan has no ${mount.purpose} volume`);
  }

  const services = [...new Set(options.services)].sort();
  if (!services.includes(options.gatewayService)) {
    throw new Error("gateway service must be part of the release adapter");
  }
  if (!services.includes("supavisor")) {
    throw new Error("release adapter must include supavisor");
  }
  for (const service of services) safeName(service, "service");

  const identity = { projectId: options.projectId, release: options.release };
  const projectLabels = labelsForProject(identity);
  const lines = [
    `# Generated by Supabase Manager; release ${options.release}`,
    "services:",
  ];
  const serviceMounts = new Map<string, NamedVolumeMount[]>();
  for (const mount of mounts) serviceMounts.set(mount.service, [...(serviceMounts.get(mount.service) ?? []), mount]);
  for (const service of services) {
    const serviceItems = serviceMounts.get(service) ?? [];
    lines.push(`  ${service}:`);
    const containerName = service === options.realtimeService
      ? `realtime-dev.${dockerProjectName(options.projectId)}_realtime`
      : projectContainerName(options.projectId, service);
    lines.push(`    container_name: ${yamlScalar(containerName)}`);
    lines.push("    labels:");
    for (const [key, value] of Object.entries(projectLabels)) {
      lines.push(`      ${yamlScalar(key)}: ${yamlScalar(value)}`);
    }
    if (serviceItems.length > 0) {
      lines.push("    volumes: !override");
      for (const mount of serviceItems) {
        const name = volumeByPurpose.get(mount.purpose)!;
        lines.push(`      - ${yamlScalar(`${name}:${mount.target}${mount.readOnly ? ":ro" : ""}`)}`);
      }
    }
    if (service === options.gatewayService) {
      lines.push("    ports: !override", `      - ${yamlScalar(`${ports.api}:8000`)}`);
      if (options.gatewayEntrypoint?.length) {
        lines.push(`    entrypoint: [${options.gatewayEntrypoint.map(yamlScalar).join(", ")}]`);
      }
    }
    if (service === "supavisor") {
      lines.push(
        "    ports: !override",
        `      - ${yamlScalar(`${ports.dbSession}:5432`)}`,
        `      - ${yamlScalar(`${ports.dbTransaction}:6543`)}`,
      );
    }
  }
  lines.push("volumes:");
  for (const volume of [...options.volumes].sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(`  ${safeName(volume.name, "volume")}:`, "    external: true");
  }
  lines.push("networks:", "  default:", `    name: ${yamlScalar(projectNetworkName(options.projectId))}`, "    labels:");
  for (const [key, value] of Object.entries(projectLabels)) {
    lines.push(`      ${yamlScalar(key)}: ${yamlScalar(value)}`);
  }
  lines.push("x-supabase-manager:", `  project-id: ${yamlScalar(options.projectId)}`, `  project-name: ${yamlScalar(dockerProjectName(options.projectId))}`);
  return `${lines.join("\n")}\n`;
}
