create table {{tableName}} (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  task text check (char_length(task) > 3),
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table {{tableName}} enable row level security;
create policy "Individuals can create {{tableName}}" on {{tableName}} for
    insert with check (auth.uid() = user_id);
create policy "Individuals can view their own {{tableName}}" on {{tableName}} for
    select using ((select auth.uid()) = user_id);
create policy "Individuals can update their own {{tableName}}" on {{tableName}} for
    update using ((select auth.uid()) = user_id);
create policy "Individuals can delete their own {{tableName}}" on {{tableName}} for
    delete using ((select auth.uid()) = user_id);


-- https://supabase.com/docs/guides/realtime/subscribing-to-database-changes#enable-postgres-changes
BEGIN;

DROP publication IF EXISTS supabase_realtime;

CREATE publication supabase_realtime;

COMMIT;

ALTER publication supabase_realtime ADD TABLE {{tableName}};


INSERT INTO storage.buckets(id,name) VALUES ('{{bucketName}}','{{bucketName}}');

CREATE POLICY "allow access to authenticated users {{bucketName}}"
ON storage.objects
FOR ALL
TO authenticated
USING (bucket_id = '{{bucketName}}')
WITH CHECK (bucket_id = '{{bucketName}}');
